### ISSUE TITLE
Can't swith zh/en by pressing Shift key

### ISSUE THREAD

**Issue by twlkyao** [lotem/rime.py#8]
Why I can't switch zh/en by pressing Shift key? My Operating System is Ubuntu12.04, neither <kbd>Shift</kbd> or <kbd>F4</kbd> works.

**Comment by lotem** [comment]
Sorry, I don't know Why You Can't, without further information.
I can confirm it works on Ubuntu 12.04, so this is probably not a bug.

Check your default.yaml and the log file to see if there are errors.

**Comment by lotem** [comment]
Wait...
You're talking about rime.py? Seriously?

**Comment by lotem** [comment]
Oh, this is tooold.
I take back what I said.
This project has been abandoned in favor of https://github.com/lotem/librime

rime.py was a previous experimental engine, and was different in design. for example:
https://github.com/lotem/rime.py/blob/master/engine/processor.py#L162
https://github.com/lotem/rime.py/blob/master/engine/composer.py#L58

You want to try
apt-get install ibus-rime
It should work as you expected.
